---

# Unix users to create everywhere.

users:
  - mxs
  - faltad

# VPN settings

netname: midearth
vpn_interface: tun0
physical_ip: "{{ ansible_enp1s0.ipv4.address }}"
network_mask: 24
network_addr: 10.0.0.0

# Geo BT

geo_user: "geo-bt"

# Shards

shards:
  - name: "8a00862"
    port: 7000
    workers: ["gamgee", "bombadil"]
  - name: "eb3e451"
    port: 7001
    workers: ["gamgee", "treebeard"]
  - name: "735ec68"
    port: 7002
    workers: ["treebeard", "bombadil"]
