---

# Unix users to create everywhere.

users:
  - mxs
  - faltad

# VPN settings

netname: midearth
vpn_interface: tun0
physical_ip: "{{ ansible_default_ipv4.address }}"
network_mask: 24
network_addr: 10.0.0.0

# Geo BT

geo_user: "geo-bt"

# Geo Layout

geo:
  # This will define the sharding strategy: all points inside the
  # rectangle below will be divided in (number of shards - 1),
  # everything outside will default to a fallback shard.
  #
  # Tuples below are [lat, long].
  - area: "fr"
    bottom_left: [44.00, -5.00]
    top_right: [51.00, 7.50]

  # For any point not in the previously defined areas, a dedicated
  # area is set as a default.
  - area: "default"

# Shards

dev_shards:
  - name: "8a00862"
    area: "default"
    hosts: ["gamgee", "bombadil"]
    mixer_port: 8000
    worker_port: 7000
  - name: "eb3e451"
    area: "fr"
    hosts: ["gamgee", "treebeard"]
    mixer_port: 8001
    worker_port: 7001
  - name: "735ec68"
    area: "fr"
    hosts: ["treebeard", "bombadil"]
    mixer_port: 8002
    worker_port: 7002

prod_shards:
  - name: "8a00862"
    area: "default"
    hosts: ['beorn']
    worker_port: 7000
    mixer_port: 8000
  - name: "eb3e451"
    area: "fr"
    hosts: ['beorn']
    worker_port: 7001
    mixer_port: 8001

# GP1-M
shards:
  - name: "8a00862"
    area: "default"
    hosts: ['sackville', 'elrond']
    worker_port: 7000
    mixer_port: 8000
  - name: "f3aebb4"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7001
    mixer_port: 8001
  - name: "dd4e7ff"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7002
    mixer_port: 8002
  - name: "eb3e451"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7003
    mixer_port: 8003
  - name: "f3aebb5"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7004
    mixer_port: 8004
  - name: "f3aebb6"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7005
    mixer_port: 8005
  - name: "f3aebb7"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7006
    mixer_port: 8006
  - name: "f3aebb8"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7007
    mixer_port: 8007
  - name: "f3aebb9"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7008
    mixer_port: 8008
  - name: "b3aebb4"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7011
    mixer_port: 8011
  - name: "bd4e7ff"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7012
    mixer_port: 8012
  - name: "bb3e451"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7013
    mixer_port: 8013
  - name: "b3aebb5"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7014
    mixer_port: 8014
  - name: "b3aebb6"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7015
    mixer_port: 8015
  - name: "b3aebb7"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7016
    mixer_port: 8016
  - name: "b3aebb8"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7017
    mixer_port: 8017
  - name: "b3aebb9"
    area: "fr"
    hosts: ['sackville', 'elrond']
    worker_port: 7018
    mixer_port: 8018
