---

# Handlers to restart/reload tinc.

- name: restart tinc
  service:
    name: tinc@{{ netname }}
    state: restarted

- name: reload tinc
  service:
    name: tinc@{{ netname }}
    state: reloaded
