---

- name: dev playbook
  hosts: gamgee
  tasks:
  - name: "generate mixer config file"
    bt_shard:
      geo: "{{ geo }}"
      shards: "{{ shards }}"
      dest: "/home/{{ geo_user }}/bt/{{ item.name }}/etc/mixer.yml"
      mixer_ip: "{{ vpn_ip }}"
      mixer_port: "{{ item.mixer_port }}"
    when: inventory_hostname is in item.hosts
    loop: "{{ shards }}"
