---

- hosts: all
  gather_facts: no
  tasks:
    - name: restart worker jobs
      become_user: "{{ geo_user }}"
      become: yes
      args:
        chdir: "/home/{{ geo_user}}/bt/{{ item.name }}"
      command: ./all.bash worker restart
      loop: "{{ shards }}"
      when: inventory_hostname in item.hosts

    - name: restart mixer jobs
      become_user: "{{ geo_user }}"
      become: yes
      args:
        chdir: "/home/{{ geo_user}}/bt/{{ item.name }}"
      command: ./all.bash mixer restart
      loop: "{{ shards }}"
      when: inventory_hostname in item.hosts
