---

- hosts: all
  gather_facts: no
  tasks:
    - name: start worker jobs
      args:
        chdir: "/home/{{ geo_user}}/bt/{{ item.name }}"
      command: ./all.bash worker start
      loop: "{{ shards }}"
      when: inventory_hostname in item.hosts

    - name: start mixer jobs
      args:
        chdir: "/home/{{ geo_user}}/bt/{{ item.name }}"
      command: ./all.bash mixer start
      loop: "{{ shards }}"
      when: inventory_hostname in item.hosts
