---

- hosts: all
  gather_facts: no
  tasks:
    - name: stop worker jobs
      args:
        chdir: "/home/{{ geo_user}}/bt/{{ item.name }}"
      command: ./all.bash worker stop
      loop: "{{ shards }}"
      when: inventory_hostname in item.hosts

    - name: stop mixer jobs
      args:
        chdir: "/home/{{ geo_user}}/bt/{{ item.name }}"
      command: ./all.bash mixer stop
      loop: "{{ shards }}"
      when: inventory_hostname in item.hosts
