---

- hosts: all
  gather_facts: no
  tasks:
    - name: stop worker jobs
      become_user: "{{ geo_user }}"
      become: yes
      args:
        chdir: "/home/{{ geo_user}}/bt/{{ item.name }}"
      command: ./all.bash worker stop
      loop: "{{ shards }}"
      when: inventory_hostname in item.hosts

    - name: stop mixer jobs
      become_user: "{{ geo_user }}"
      become: yes
      args:
        chdir: "/home/{{ geo_user}}/bt/{{ item.name }}"
      command: ./all.bash mixer stop
      loop: "{{ shards }}"
      when: inventory_hostname in item.hosts
