---

- name: set up base system configuration
  import_playbook: base.yml

- name: set up intra-cluster cluster networking
  import_playbook: network.yml

- name: set up geo backtracer
  import_playbook: geo.yml
