---

# Setup the Geo-Backtracer.

- name: "create volume directory for shards"
  file:
    owner: "{{ geo_user }}"
    path: "/data/bt/{{ item.name }}"
    state: directory
    mode: 0755
  when: inventory_hostname is in item.hosts
  loop: "{{ shards }}"

- name: "create bt directory for geo-bt user"
  file:
    owner: "{{ geo_user }}"
    path: "/home/{{ geo_user }}/bt"
    state: directory
    mode: 0755

- name: "add symlinks to data directory for shards"
  file:
    src: "/data/bt/{{ item.name }}"
    path: "/home/{{ geo_user }}/bt/{{ item.name }}"
    state: link
    owner: "{{ geo_user }}"
    mode: 0755
  when: inventory_hostname is in item.hosts
  loop: "{{ shards }}"

- name: "create directories for shards"
  file:
    owner: "{{ geo_user }}"
    path: "/home/{{ geo_user }}/bt/{{ item[0].name }}/{{ item[1] }}"
    state: directory
    mode: 0755
  when: inventory_hostname is in item[0].hosts
  with_nested:
    - "{{ shards }}"
    - ['bin', 'log', 'etc', 'data']

- name: "create worker config file"
  template:
    owner: "{{ geo_user }}"
    src: templates/worker.yml
    dest: "/home/{{ geo_user }}/bt/{{ item.name }}/etc/worker.yml"
  when: inventory_hostname is in item.hosts
  loop: "{{ shards }}"

- name: "create client config file"
  template:
    owner: "{{ geo_user }}"
    src: templates/client.yml
    dest: "/home/{{ geo_user }}/bt/{{ item.name }}/etc/client.yml"
  when: inventory_hostname is in item.hosts
  loop: "{{ shards }}"

- name: "generate mixer config file"
  bt_shard:
    geo: "{{ geo }}"
    shards: "{{ shards }}"
    history: "{{ history }}"
    dest: "/home/{{ geo_user }}/bt/{{ item.name }}/etc/mixer.yml"
    mixer_ip: "{{ vpn_ip }}"
    mixer_port: "{{ item.mixer_port }}"
  when: inventory_hostname is in item.hosts
  loop: "{{ shards }}"

- name: "install geo-bt"
  become_user: "{{ geo_user }}"
  become: yes
  make:
    chdir: "/home/{{ geo_user }}/src"
    target: install
    params:
      INSTALL_DIR: "/home/{{ geo_user }}/bt/{{ item.name }}"
  when: inventory_hostname is in item.hosts
  loop: "{{ shards }}"
