---

# Setup the Geo-Backtracer.

- name: "create directory structure"
  file:
    owner: "{{ geo_user }}"
    path: "/data/bt/{{ item[0].name }}/{{ item[1] }}"
    state: directory
    mode: 0755
  with_nested:
    - "{{ shards }}"
    - ['log', 'etc', 'bin', 'data']
  when: inventory_hostname in item[0].workers

- name: "add symlinks to data path"
  file:
    src: "/data/bt/{{ item[0].name }}/{{ item[1] }}"
    path: "/home/{{ geo_user }}/bt/{{ item[0].name }}/{{ item[1] }}"
    state: link
    owner: "{{ geo_user }}"
    mode: 0755
  with_nested:
    - "{{ shards }}"
    - ['log', 'etc', 'bin', 'data']
  when: inventory_hostname in item[0].workers

- name: "create worker config file"
  template:
    src: templates/worker.yml
    dest: "/home/{{ geo_user }}/bt/{{ item.name }}/etc/worker.yml"
  loop: "{{ shards }}"
  when: inventory_hostname in item.workers

- name: "generate mixer config file"
  bt_shard:
    geo: "{{ geo }}"
    shards: "{{ shards }}"
    dest: "/home/{{ geo_user }}/bt/{{ item.name }}/etc/mixer.yml"
    mixer_ip: "{{ vpn_ip }}"
    mixer_port: "{{ 8000 + idx }}"
  loop: "{{ shards }}"
  loop_control:
    index_var: idx
  when: inventory_hostname in item.workers

- name: "install geo-bt"
  make:
    chdir: "/home/{{ geo_user }}/src"
    target: install
    params:
      INSTALL_DIR: "/home/{{ geo_user }}/bt/{{ item.name }}"
  loop: "{{ shards }}"
  when: inventory_hostname in item.workers
